### ISSUE TITLE
Tutorial Needed

### ISSUE THREAD

**Issue by NirantK** [litaotao/IPython-Dashboard#2]
Hello @litaotao ! 
Found your project via [Domino Datalab](http://blog.dominodatalab.com/lesser-known-ways-of-using-notebooks/). Excellent work. 

This is extremely useful and much needed. Can you please write a quick introductory tutorial on using your project? Or a README with instructions? It would help us contribute to your project as well as increase its usage.

**Comment by litaotao** [comment]
@NirantK  hi, yes, that's in the branch : https://github.com/litaotao/IPython-Dashboard/tree/v-0.1.2-visualiza-table   which will be released in two days, I'm planning to add a usage code snippet and ipython notebook tutorial before merge v-0.1.2 , also with a contribute guide. 

thanks for your advice, feel free to star this.

**Comment by NirantK** [comment]
Starred. 

Thanks for the quick turnaround. Looking forward to the release. How can I make sure that I know about it?

**Comment by litaotao** [comment]
hi, you'll get a notification from github when I close this issue after the release.

**Comment by litaotao** [comment]
@NirantK hi, I just merged a branch to master, also with a simple [tutorial](https://github.com/litaotao/IPython-Dashboard#usage)

there will be more tutorials later on.

will close this issue, thanks
